title: MSVC Gallery with Face Matching
description: 5 Semesterarbeit für Cloud Native Engineer Studium
theme: just-the-docs

url: https://noluchs.github.io/5SEM
aux_links:
   Projektplanung: https://noluchs.atlassian.net/jira/software/projects/SCRUM/boards/1



mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.8.0"