#Base image
FROM node:lts-alpine3.17 as builder

# Set the working directory
WORKDIR /app

# Copy the package.json
COPY ./package.json /app/package.json

# install project dependencies
RUN npm install

COPY . /app
RUN npm run build

# production env
FROM nginx:1.23.3-alpine-slim

COPY --from=builder /app/dist /usr/share/nginx/html
COPY --from=builder /app/nginx.conf /etc/nginx/

EXPOSE 3000

CMD [ "nginx", "-g", "daemon off;" ]
