# Base image
FROM node:lts-alpine3.17

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port that the Vite development server listens on
EXPOSE 3000

# Start the Vite development server with the --host flag
CMD ["npm", "run", "dev", "--", "--host"]