# Base python package
FROM python:3.12-slim

# Working directory
WORKDIR /app

# Copy the dependencies
COPY requirements.txt requirements.txt

# Install the dependencies
RUN pip install -r requirements.txt

# Install Gunicorn
RUN pip install gunicorn

# for flask web server
EXPOSE 5000

# add files
ADD . /app

# This is the runtime command for the container
# Add below line if not using docker-compose
CMD [ "gunicorn", "-b", "0.0.0.0:5001", "wsgi:app" ]

