"""Initial migration

Revision ID: a3693eaff82a
Revises: 
Create Date: 2024-06-24 20:22:51.597335

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a3693eaff82a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('galleries')
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_constraint('photos_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'gallery', ['gallery_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('photos_ibfk_1', 'galleries', ['gallery_id'], ['id'])

    op.create_table('galleries',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
